import React from "react"

function Moonfall(props){
    return(<div>
        <h2>Moonfall</h2>
        <a href="https://github.com/Natecat4444/Moonfall">Github Repo</a>
        <p>Part of the Cognixia jump program, this group project utilizes a MySQL database to allow users to maintain a list of shows and where they are with them.
            The front end is generated by three java servlets.
        </p>
    </div>)
}

export default Moonfall