import React, {useState} from "react";

function Battleship(props){
    return(<div>
        <a href="https://github.com/Natecat4444/BattleshipCollab">Github Repo</a>
        <p>This early project was a collboration between me and a friend.
             It was intended to be a two player game which could be played on the same computer or on two seperate ones with an open port and ip address.
              Although it has yet to be finished, it was a fun exercise in planning and rule making.</p>
    </div>)
}

function Planner(props){
    return(<div>
        <a href="https://github.com/Natecat4444/Planner">Github Repo</a>
        <p>A project placed on the back burner during college, this is a java application that uses a MySQL database to track to do items.
             One cool feature that I did manage to finish is the SQL processor, which will create the SQL database if not already installed.
              This feature was also inteded to be used for updates if I ever felt the need to modify the database.</p>
    </div>)
}

function SteamAPI(props){
    return(<div>
        <a href="https://github.com/Natecat4444/ISTE-432-Project-SteamAPI">Github Repo</a>
        <p>A group java project done in college, this project was extensively planned before execution, with all documentation being availible in the readme.
            This application calls a steam api to retieve news articles published by game devlopers and display them in a javafx front end. The program also uses a 
            SQL database to allow the user/users to store their favorites.
        </p>
    </div>)
}

function Moonfall(props){
    return(<div>
        <a href="https://github.com/Natecat4444/Moonfall">Github Repo</a>
        <p>Part of the Cognixia jump program, this group project utilizes a MySQL database to allow users to maintain a list of shows and where they are with them.
            The front end is generated by three java servlets.
        </p>
    </div>)
}

function Defaultview(props){
    return(<div>
        <p>Please select a project for a description and dedicated link</p>
    </div>)
}

function Home(props){
    const[viewcomp, setveiwcomp] = useState(0);
    const styles = {
        'textAlign': 'center',
        'paddingLeft': '25%',
        'paddingRight': '25%'
    }

    const handleSubmit = (event) => {
        console.log("Handle sublit called")
        console.log(event.target.value)
        setveiwcomp(viewcomp)
        console.log(viewcomp)
        event.preventDefault();

    }

    let view = <Defaultview />;

    console.log(viewcomp);
    if(viewcomp == 1){
        view = <Battleship />;
        console.log("view set to battleship")
    }

    if(viewcomp == 2){
        view = <Planner />;
        console.log("view set to battleship")
    }

    if(viewcomp == 3){
        view = <SteamAPI />;
        console.log("view set to battleship")
    }

    if(viewcomp == 4){
        view = <Moonfall />;
        console.log("view set to battleship")
    }
    
    return(
        <div style={styles}>
            <p><a href='https://github.com/Natecat4444'>Github Profile</a></p>
            <form>
                <select name={viewcomp} onChange={(event) => setveiwcomp(event.target.value)}>
                    <option>Select Project</option>
                    <option name={viewcomp} value={1}>Battleship</option>
                    <option name={viewcomp} value={2}>Planner</option>
                    <option name={viewcomp} value={3}>SteamAPI</option>
                    <option name={viewcomp} value={4}>Moonfall</option>
                </select>
               
            </form>

            {view}

        </div>
    );
}

export default Home;